# Check https://circleci.com/docs/2.0/language-java/ for more details
version: 2
shared: &shared
  working_directory: ~/repo

  environment:
    #    JVM_OPTS: -Xmx3200m
    TERM: dumb

  steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "build.gradle.kts" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

    - run: gradle dependencies

    - save_cache:
        paths:
          - ~/.gradle
        key: v1-dependencies-{{ checksum "build.gradle.kts" }}

    # run tests!
    - run: gradle check


jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    <<: *shared
  build-jdk8:
    docker:
      - image: circleci/openjdk:8-jdk
    <<: *shared

workflows:
  version: 2
  build_on_all:
    jobs:
      - build
      - build-jdk8